// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqjihfdyqaymddlmovkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxamloZmR5cWF5bWRkbG1vdmtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNDE2NjcsImV4cCI6MjA2MzcxNzY2N30.lUjAocB-kIzx3D7KvRLebpnSH5t82aBIfysMHi_Xyw8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);